[tool.ruff]
target-version = "py311"
line-length = 120
ignore = [
    "E731",
    "E402",
    "N812", # Uppercase import (for nn.functional as F)
]
select = [
    "F",   # pyflakes
    "UP",  # pyupgrade
    "I", # isort
    "ERA", # eradicate
    "NPY", # numpy
    "N", # pep8-naming
    "UP", # pyupgrade
]
exclude = ["./data/"]

[tool.mypy]
plugins = "pydantic.mypy"
ignore_missing_imports = true
exclude = ["./data/"]